---
version: '3'

services:
  webapp:
    image: timmo001/quiz-webapp
    environment:
      NODE_ENV: production
    ports:
      - 8234:443
    volumes:
      - ~/ssl:/ssl
  ws:
    image: quiz-ws
    build: .
    environment:
      CERTIFICATES_DIR: /ssl
    ports:
      - 8080:8080
    volumes:
      - ~/ssl:/ssl
